介绍了pytorch中张量tensor的初始化、数据类型转换、数据共享机制和常见的数学操作

In [1]:
import torch
torch.__version__

'1.0.1.post2'

### 1. 序列化操作

In [ ]:
# 保存
torch.save(obj, f)

In [ ]:
# 加载
torch.load(f)

### 2. 两张量的比较操作

In [2]:
# 逐元素比较元素相等性torch.eq(input, other, out=None)
torch.eq(torch.Tensor([[1, 2], [3, 4]]), torch.Tensor([[1, 1], [4, 4]]))

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [3]:
# 比较两个张量是否完全相等（形状和对应的元素值）torch.equal(tensor1, tensor2) → bool
torch.equal(torch.Tensor([1, 2]), torch.Tensor([1, 2]))

True

In [4]:
# torch.ge(input, other, out=None) → Tensor  逐元素比较input和other是否大于等于
# torch.gt(input, other, out=None) → Tensor 逐元素比较input和other是否大于
# torch.le(input, other, out=None) → Tensor  逐元素比较input和other是否小于等于
# torch.lt(input, other, out=None) → Tensor 逐元素比较input和other是否小于

In [6]:
# 取所有元素中的最大值
a = torch.randn(1, 3)
torch.max(a)

tensor(0.8785)

In [8]:
# 返回输入张量给定维度上每行的最大值，并同时返回每个最大值的位置索引。torch.max(input, dim, max=None, max_indices=None) -> (Tensor, LongTensor)
a = torch.randn(4, 4)
torch.max(a, 1)

(tensor([1.3239, 0.0625, 1.1158, 0.9539]), tensor([0, 2, 2, 3]))

In [9]:
# 返回两个tensor中对应元素的最大值
a = torch.randn(4)
b = torch.randn(4)
torch.max(a,b)

tensor([-0.3595,  0.7085,  1.0766,  1.5260])

### 3. 随机抽样操作

#### 3.1 设定随机种子

In [10]:
# 设定生成随机数的种子，并返回一个 torch._C.Generator 对象.
torch.manual_seed(66)

In [11]:
# 返回生成随机数的原始种子值
torch.initial_seed()

66

In [12]:
# 返回随机生成器状态
torch.get_rng_state()

tensor([66,  0,  0,  ...,  0,  0,  0], dtype=torch.uint8)

#### 3.2 数据分布生成

In [15]:
# 伯努利分布torch.bernoulli(input, out=None) → Tensor
# input中各元素为伯努利分布的概率分布（各元素值必须在0-1），返回一个同shape的0-1张量
torch.bernoulli(torch.rand(3,3))

tensor([[0., 0., 0.],
        [1., 1., 0.],
        [1., 0., 0.]])

In [18]:
# 多项式分布torch.multinomial(input, num_samples,replacement=False, out=None) → LongTensor
# input中各行表示多项式分部概率（不能全部为0，会自动进行weight的归一化）
# replacement=True表示有放回采样
weights = torch.Tensor([[0, 10, 3, 0], [1,2,3,4]])
torch.multinomial(weights, 4, replacement=True)

tensor([[2, 1, 1, 1],
        [0, 2, 0, 3]])

In [33]:
# 正态分布生成
# mean和std为对应的两个张量，每个（i，j）表示一个独立的分布进行采用
bb=torch.Tensor(2,2)
torch.normal(mean=torch.linspace(0,1,10), std=torch.linspace(0,1,10))

tensor([ 0.0000,  0.1075,  0.1147, -0.1127,  0.7183,  0.9590,  2.1193,  0.6652,
         1.4297,  1.6131])

In [31]:
# 同均值，不同方差
torch.normal(mean=0.5, std=torch.linspace(1, 6,10))

tensor([ 0.7449, -1.7071, -4.6307,  4.2131,  3.6009,  4.9264, -3.2759, -1.5770,
        -2.8447,  8.8612])

In [34]:
# 同方差，不同均值
torch.normal(std=0.5, mean=torch.linspace(1, 6,10))

tensor([0.7144, 2.1387, 1.8347, 2.5222, 2.9733, 4.8278, 4.4823, 5.1017, 6.0186,
        6.0603])

### 4. 张量的索引、切片、连接操作

In [36]:
x = torch.randn(2,3)
x

tensor([[ 1.1693,  0.4543, -1.4110],
        [ 0.3194,  0.6029,  0.4305]])

In [38]:
# 沿着某个已有的axis进行拼接  torch.cat(inputs, dimension=0) → Tensor
print(torch.cat((x,x), dim=0))   # dim=0即行方向
print(torch.cat((x,x), dim=1))   # dim=0即行方向

tensor([[ 1.1693,  0.4543, -1.4110],
        [ 0.3194,  0.6029,  0.4305],
        [ 1.1693,  0.4543, -1.4110],
        [ 0.3194,  0.6029,  0.4305]])
tensor([[ 1.1693,  0.4543, -1.4110,  1.1693,  0.4543, -1.4110],
        [ 0.3194,  0.6029,  0.4305,  0.3194,  0.6029,  0.4305]])


In [39]:
# 沿着某个已有的axis进行分块（cat的反向操作） torch.chunk(tensor, chunks, dim=0)
# chunks为个数
x = torch.randn(2,3)
y = torch.cat((x,x), dim=0)   # 先拼接
torch.chunk(y, 2, dim=0)

(tensor([[-0.9716,  0.0812,  0.3391],
         [-0.7621,  1.3135, -2.3922]]), tensor([[-0.9716,  0.0812,  0.3391],
         [-0.7621,  1.3135, -2.3922]]))

In [67]:
# 沿着某个已有的axis进行分块（cat的反向操作） torch.chunk(tensor, split_size, dim=0)
# split_size为每块的个数，如果沿指定维的张量形状大小不能被整分，则最后一个分块会小于其它分块
x = torch.randn(3,3)
print(x)
print(torch.split(x, 2, dim=0))

tensor([[ 1.5554, -0.0718,  0.3904],
        [-1.7151, -0.1270,  1.3241],
        [ 0.7957,  1.1578,  0.3443]])
(tensor([[ 1.5554, -0.0718,  0.3904],
        [-1.7151, -0.1270,  1.3241]]), tensor([[0.7957, 1.1578, 0.3443]]))


In [43]:
# 沿着指定维度dim对输入进行index切片, torch.index_select(input, dim, index, out=None) → Tensor
# index为一个LongTensor类型
# 返回的张量不与原始张量共享内存空间
indices=torch.LongTensor([0,2]) 
torch.index_select(x,0,index=indices)   # 验证dim=0的方向取其中的0、2

tensor([[-0.0326,  1.6117,  1.4897,  0.7246],
        [-1.0571, -0.7701, -0.0142,  0.2322]])

In [54]:
z = x[[0,2]]   # 同这种直接切片，同样会生成一个新的
print(z)
print(x)

tensor([[-0.0326,  1.6117,  1.4897,  0.7246],
        [-1.0571, -0.7701, -0.0142,  0.2322]])
tensor([[-0.0326,  1.6117,  1.4897,  0.7246],
        [ 0.0246,  1.1675,  1.0860, -0.9570],
        [-1.0571, -0.7701, -0.0142,  0.2322]])


In [64]:
# 掩码选择torch.masked_select(input, mask, out=None) → Tensor
# input和mask的shape必须一样,mask必须为type类型张量
# 返回值为一个一维向量，元素为对应mask元素为0的
x = torch.randn(2, 3)
mask = torch.bernoulli(torch.rand(2,3)).byte()
y = torch.masked_select(x, mask)
print(x)
print(mask)
print(y)

tensor([[1.0578, 1.1777, 0.1858],
        [0.9285, 0.2916, 0.7150]])
tensor([[1, 1, 1],
        [0, 0, 1]], dtype=torch.uint8)
tensor([1.0578, 1.1777, 0.1858, 0.7150])


In [65]:
# torch.nonzero(input, out=None) → LongTensor返回非零元素索引的张量
# 如果输入input有n维，则输出的索引张量output的形状为 z x n, 这里 z 是输入张量input中所有非零元素的个数。
torch.nonzero(torch.Tensor([[0.6, 0.0, 0.0, 0.0],[0.0, 0.4, 0.0, 0.0],[0.0, 0.0, 1.2, 0.0],[0.0, 0.0, 0.0,-0.4]]))

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3]])

In [68]:
# torch.squeeze(input, dim=None, out=None)沿着指定轴进行挤压（若指定轴为1）
# 若不声明dim，则会在所有值为1的dim上进行挤压
# squeeze操作会共享内存
x = torch.zeros(2,1,2,1,2)
print(x.size())
y = torch.squeeze(x)
print(y.size())
z = torch.squeeze(x,1)
print(z.size())
print(x.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 2, 1, 2])
torch.Size([2, 1, 2, 1, 2])


In [73]:
# torch.unsqueeze(input, dim, out=None) 返回一个新的张量，对输入的制定位置插入维度 1
# 返回张量与输入张量共享内存
# 如果dim为负，则将会被转化dim+input.dim()+1
x = torch.Tensor([1, 2, 3, 4])
torch.unsqueeze(x,0)

tensor([[1., 2., 3., 4.]])

In [72]:
# torch.t(input, out=None) → Tensor  二维张量的转置，等同于transpose(input, 0, 1)
x = torch.randn(2, 3)
print(x)
print(torch.transpose(x,0,1))

tensor([[-0.1753,  1.3432, -1.6604],
        [-1.4470,  1.2004,  0.1172]])
tensor([[-0.1753, -1.4470],
        [ 1.3432,  1.2004],
        [-1.6604,  0.1172]])


In [71]:
# torch.transpose(input, dim0, dim1, out=None) → Tensor 交换dim0和dim1两个轴
# 数据共享
x = torch.randn(2, 3)
print(x)
print(torch.transpose(x,0,1))

tensor([[-1.6668,  1.2261,  0.4297],
        [-0.2251, -1.6966,  0.0579]])
tensor([[-1.6668, -0.2251],
        [ 1.2261, -1.6966],
        [ 0.4297,  0.0579]])


### 5. CPU和GPU间的移动

tensor默认存储在CPU中，可以使用cuda方法移动到GPU中

In [75]:
tensor_cpu = torch.zeros(3,4)
tensor_cpu.type()

'torch.FloatTensor'

In [ ]:
# 并不共享内存，本计算机没GPU，GPU上跑下来的结果为'torch.cuda.FloatTensor'
tensor_gpu = tensor_cpu.cuda()
tensor_gpu.type()

In [77]:
#使用torch.cuda.is_available()来确定是否有cuda设备
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [ ]:
#将tensor传送到设备
gpu_x=cpu_x.to(device)
gpu_x.type()